name: my_member_link
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  camera: ^0.11.0+2
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  http: ^1.2.2
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/logoo.png
  - assets/images/gallery.png

